In [1]:
import numpy as np

In [2]:
#Assigning Input features:
input_values = np.array([[5,6], [4,3], [8,22], [32,56]])
input_values.shape
input_values

array([[ 5,  6],
       [ 4,  3],
       [ 8, 22],
       [32, 56]])

In [3]:
#Assign target output:
out = np.array([1,0,0,1])
out = out.reshape(4,1)
out.shape

(4, 1)

In [4]:
out

array([[1],
       [0],
       [0],
       [1]])

In [5]:
#Assign weights:
weights = np.array([[0.35], [0.65]])
weights

array([[0.35],
       [0.65]])

In [6]:
#Adding bias:
b = 0.045


In [29]:
#Activation function:
def ReLU_af(x):
    return (max(0,x))

SyntaxError: invalid syntax (1227611632.py, line 2)

In [34]:
ReLU_af(-0.3)

0

In [9]:
def derivative_s(x):
    return ReLU_af_af(x) * (1-sigmoid_af(x))

In [10]:
#Updating the weights:
for epochs in range(100):
    input_array = input_values
    
    weightedsum = np.dot(input_array, weights) + b
    firstoutput = sigmoid_af(weightedsum)
    
    error = firstoutput - out
    total_error = np.square(np.subtract(firstoutput, out)).mean()
    
    first_der = error
    second_der = derivative_s(firstoutput)
    derivative = first_der * second_der
    
    t_input = input_values.T
    final_derivative = np.dot(t_input, derivative)
    
    #weights:
    weights = weights - 0.5*(final_derivative)
    
    #update bias:
    for i in derivative:
        b = b - 0.5*i
        
        
        
    

print(weights)
print(b)

[[ 9.3053877 ]
 [-4.25349697]]
[-12.02636602]


In [26]:
#Predictions:
predictions = np.array([3,4])

results = np.dot(predictions, weights) + b
print(results)

res = sigmoid_af(results)
print(res)
print(1/(1 + np.exp(-results)))

[-1.12419083]
[0.24523476]
[0.24523476]


In [24]:
sigmoid_af(results)

array([0.24523476])